#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Mar 26, 2020 03:34:18 PM CET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
import random
import time
import first_support
import _thread

def randomColor():    
        r = lambda: random.randint(0,255)
        return '#%02X%02X%02X' % (r(),r(),r())

def change_color(Tk):
        while(True):
                Tk.Frame1.configure(background=randomColor())
                Tk.Frame1_3.configure(background=randomColor())
                Tk.Frame2.configure(background=randomColor())
                Tk.Frame3.configure(background=randomColor())
                Tk.Frame4.configure(background=randomColor())
                Tk.Frame5.configure(background=randomColor())
                Tk.Frame6.configure(background=randomColor())
                Tk.Frame7.configure(background=randomColor())
                Tk.Frame8.configure(background=randomColor())
                time.sleep(2);

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    first_support.init(root, top)
    _thread.start_new_thread( change_color, (top,) )
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    first_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+475+183")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(0, 0)
        top.title("I'm here !")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

       

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.017, rely=0.022, height=51, width=264)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Hi, it's my first day like Python app =)''')

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.067, rely=0.156, relheight=0.167
                , relwidth=0.208)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#ff0000")

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.267, rely=0.156, relheight=0.167
                , relwidth=0.208)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d9d9d9")

        self.Frame3 = tk.Frame(top)
        self.Frame3.place(relx=0.467, rely=0.156, relheight=0.167
                , relwidth=0.208)
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#d9d9d9")

        self.Frame1_3 = tk.Frame(top)
        self.Frame1_3.place(relx=0.267, rely=0.333, relheight=0.167
                , relwidth=0.208)
        self.Frame1_3.configure(relief='groove')
        self.Frame1_3.configure(borderwidth="2")
        self.Frame1_3.configure(relief="groove")
        self.Frame1_3.configure(background="#d9d9d9")
        self.Frame1_3.configure(highlightbackground="#d9d9d9")
        self.Frame1_3.configure(highlightcolor="black")

        self.Frame4 = tk.Frame(top)
        self.Frame4.place(relx=0.067, rely=0.333, relheight=0.167
                , relwidth=0.208)
        self.Frame4.configure(relief='groove')
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief="groove")
        self.Frame4.configure(background="#d9d9d9")

        self.Frame5 = tk.Frame(top)
        self.Frame5.place(relx=0.467, rely=0.333, relheight=0.167
                , relwidth=0.208)
        self.Frame5.configure(relief='groove')
        self.Frame5.configure(borderwidth="2")
        self.Frame5.configure(relief="groove")
        self.Frame5.configure(background="#d9d9d9")

        self.Frame6 = tk.Frame(top)
        self.Frame6.place(relx=0.067, rely=0.511, relheight=0.167
                , relwidth=0.208)
        self.Frame6.configure(relief='groove')
        self.Frame6.configure(borderwidth="2")
        self.Frame6.configure(relief="groove")
        self.Frame6.configure(background="#d9d9d9")

        self.Frame7 = tk.Frame(top)
        self.Frame7.place(relx=0.267, rely=0.511, relheight=0.167
                , relwidth=0.208)
        self.Frame7.configure(relief='groove')
        self.Frame7.configure(borderwidth="2")
        self.Frame7.configure(relief="groove")
        self.Frame7.configure(background="#d9d9d9")

        self.Frame8 = tk.Frame(top)
        self.Frame8.place(relx=0.467, rely=0.511, relheight=0.167
                , relwidth=0.208)
        self.Frame8.configure(relief='groove')
        self.Frame8.configure(borderwidth="2")
        self.Frame8.configure(relief="groove")
        self.Frame8.configure(background="#d9d9d9")

if __name__ == '__main__':
    vp_start_gui()





